title: Microsoft AI Agentic Workshop
description: This workshop teaches you how to design, build, govern, and operate AI applications and agents using Microsoft Foundry, Microsoft Agent Framework, Microsoft 365 Copilot, Copilot Studio, MCP, A2A, observability, evaluations, guardrails, and AI Gateway patterns.
theme: just-the-docs

# url: https://microsoft.github.io/TechWorkshop-L300-AI-Apps-and-agents/

aux_links:
  "Microsoft AI Agentic Workshop": 
    - "https://github.com/microsoft/TechWorkshop-L300-AI-Apps-and-agents"
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red